### ISSUE TITLE
ModuleNotFoundError in CANA Tutorial

### ISSUE THREAD

**Issue by VitaminBrad** [rionbr/CANA#10]
Hello!

I encountered the following error when attempting to to import cana:

`from cana import BooleanNode`

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-7-2dc8e04d9be2> in <module>
> ----> 1 from cana import BooleanNode
> 
> ~/anaconda3/envs/thesis/lib/python3.8/site-packages/cana/__init__.py in <module>
>      18 
>      19 #
> ---> 20 from boolean_network import BooleanNetwork
>      21 from boolean_node import BooleanNode
>      22 from utils import *
> 
> ModuleNotFoundError: No module named 'boolean_network'

Do you know what might be causing this? 
I installed cana via `pip install cana` Thank you!

**Comment by rionbr** [comment]
Hey @VitaminBrad, thanks for using CANA and for submitting the issue.
The import you are looking for is
```
from cana.boolean_node import BooleanNode                                                                                                                                                              
```

FYI, the current version of CANA on pip is not really python3 friendly. I recommend you install the latest development version straight from github. We need to release a new version but we haven't had the time to do so.

Let us know if you run into additional problems.

With kind regards,
