### ISSUE TITLE
no drawing module

### ISSUE THREAD

**Issue by stas-g** [rionbr/CANA#17]
i am using cana v 0.1 and get the following error:

```python
>>> import cana
>>> from cana.drawing.canalizing_map import draw_canalizing_map_graphviz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cana.drawing'
```

ineed, when i check the submodules of `cana`, i get:

```python
>>> dir(cana)
['__all__', '__author__', '__builtins__', '__cached__', '__copyright__', '__description__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__release__', '__spec__', '__title__', '__version__', 'bns', 'boolean_network', 'boolean_node', 'canalization', 'control', 'cutils', 'datasets', 'utils']
```
with `drawing` missing. 

this might also be helpful:
```shell
xxx@zzz:~$ pip freeze | grep cana
cana @ git+git://github.com/rionbr/CANA@e87c8f74bf6a67318b856d2b14d30c925d195918
```

**Comment by rionbr** [comment]
Dear @stas-g,

Thanks for getting in touch.
Yeah, we noticed that the `drawing` module wasn't being included in the distribution of `v0.1` and we already submitted a fix in `v0.1.2`.

```python
>>> import cana
>>> cana.__version__
'0.1.2'
>>> from cana.drawing.canalizing_map import draw_canalizing_map_graphviz
>>> dir(cana)
['__all__', ... '__version__', 'drawing']
```

Can you please update to `v0.1.2` and let us know if this gets resolved?
You should be use `pip` or the latest `git` release.

Cheers,

**Comment by stas-g** [comment]
dear Rion,

many thanks for your swift response. i have downloaded cana v1.0.2. and the drawing module is there and loads fine. thank you for your help.

best,
stas

**Comment by rionbr** [comment]
Awesome! Glad we could help.
Let us know if run into issues or need any help using the package.
Cheers,
