### ISSUE TITLE
Minor installation difficutlties

### ISSUE THREAD

**Issue by jcrozum** [rionbr/CANA#24]
I ran into some trouble installing this in WIndows 11 using python 3.9 a while ago, and I was reminded of these problems when I was upgrading to 3.10 today.

1. I was not able to install via pip. The output is very long, so I'll just attach it as a text file here: 
[cana_install_output_error.txt](https://github.com/rionbr/CANA/files/9114398/cana_install_output_error.txt)

2. Fortunately, I was able to get the GitHub version to work, but I think ` pip install git+git://github.com/rionbr/CANA`  should be `pip install git+https://github.com/rionbr/CANA`. At least, the second version worked for me and the first version did not.

**Comment by rionbr** [comment]
Thanks Jordan, I'll this to a new release!
