### ISSUE TITLE
Combining Sensitivity and Activity computations

### ISSUE THREAD

**Issue by rionbr** [rionbr/CANA#8]
From Luis M. Rocha: it would be great if activity could be directly calculated by changing the aggregation operator in the existing code---at least comments should say that in the edge redundancy function, AVG yields redundancy (and indirectly effectiveness, via 1-redundancy), and MAX yields activity. Then sensitivity would be computed (with a different function) by summing the activities of all inputs, as much as effective connectivity can be computed by summing the  effectiveness of all inputs---though it can also be computed via eq. 1 where MAX must be used.

**Comment by austin-marcus** [comment]
I believe Felipe's fork (https://github.com/fcphysics/CANA) implements this feature.

**Comment by austin-marcus** [comment]
Implemented by #30.
